version: 2

updates:
  - package-ecosystem: nuget
    directory: "/src/UnMango.Xml"
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: "/test/UnMango.Xml.Test"
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: "/test/UnMango.Xml.Benchmarks"
    schedule:
      interval: daily
