trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - README.md
    - docs/*

pr:
- master
- release/*

pool: Linux

variables:
  BuildConfiguration: Release
  UnMangoFeed: 'UnMango NuGet'
  CI: true

jobs:
- job: build_test
  displayName: Build and Test
  workspace:
    clean: outputs
  steps:
  - checkout: self
  
  - task: UseDotNet@2
    displayName: Install .NET Core
    inputs:
      packageType: sdk
      useGlobalJson: true

  - bash: dotnet tool restore
    displayName: Restore .NET Tools
  
  - task: DotNetCoreCLI@2
    displayName: .NET Restore
    inputs:
      command: restore
      projects: '**/*.csproj'
      nugetConfigPath: NuGet.Config
      externalFeedCredentials: $(UnMangoFeed)   # Service Connection Name
      arguments: '-c $(BuildConfiguration)'
      verbosityRestore: Normal
  
  - task: DotNetCoreCLI@2
    displayName: .NET Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--no-restore -c $(BuildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: .NET Test
    inputs:
      command: test
      projects: '**/*[Tt]est*.csproj'
      arguments: >
        --no-build
        --no-restore
        -c $(BuildConfiguration)
        --logger trx
        --results-directory "$(Build.StagingDirectory)/TestResults"
        --filter:"Category=Unit"
        --collect:"XPlat Code Coverage"
      publishTestResults: false

  - bash: |
      dotnet tool run reportgenerator \
        -reports:$(Build.StagingDirectory)/**/coverage.cobertura.xml \
        -targetdir:$(Build.StagingDirectory)/coverlet/reports \
        -reporttypes:Cobertura
    displayName: Generate Code Coverage Report
    condition: always()

  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: always()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx' 
      searchFolder: '$(Build.StagingDirectory)'

  - task: PublishCodeCoverageResults@1
    displayName: Publish Code Coverage Results
    condition: always()
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: $(Build.StagingDirectory)/**/Cobertura.xml
      failIfCoverageEmpty: false
  
  - task: DotNetCoreCLI@2
    displayName: .NET Pack
    inputs:
      command: pack
      projects: '**/*.csproj'
      configuration: $(BuildConfiguration)
      nobuild: true
      arguments: '--no-restore -o $(Build.ArtifactStagingDirectory)'
      versioningScheme: off
      verbosityPack: Normal
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      ArtifactName: Packages
      PathtoPublish: $(Build.ArtifactStagingDirectory)
