version: 1

update_configs:
- package_manager: dotnet:nuget
  directory: /src/UnMango.Xml
  update_schedule: live
  automerged_updates:
  - match:
      dependency_type: all
      update_type: semver:patch

- package_manager: dotnet:nuget
  directory: /test/UnMango.Xml.Test
  update_schedule: live
  automerged_updates:
  - match:
      dependency_type: all
      update_type: semver:patch
